<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <!-- 设置为 true 可在编译后自动打包 .icpx 插件包 -->
    <CreateIcpx>false</CreateIcpx>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
    <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InkCanvas.PluginSdk" Version="1.7.19.9-ga6fafad8a9" PrivateAssets="all" />
    <PackageReference Include="InkCanvas.Controls" Version="1.7.19.9-ga6fafad8a9" PrivateAssets="all" />
  </ItemGroup>

  <!-- 自动将 manifest.json 复制到输出目录 -->
  <ItemGroup>
    <None Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
