name: Build

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md', 'LICENSE' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md', 'LICENSE' ]
  workflow_dispatch:

jobs:
  build:
    uses: InkCanvasForClass/community/.github/workflows/plugin-build.yml@net6
    with:
      project: SamplePlugin.csproj
      plugin_id: sample.plugin
      plugin_name: 示例插件
      plugin_description: '示例插件，演示工具栏组件动态注册'
      auto_release: true
    secrets: inherit
